name: Build and deploy JAR app to Azure Web App - gamerhub-api

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin        # or 'microsoft', both OK
          java-version: '21'
          cache: maven                 # speed up builds

      - name: Build with Maven
        working-directory: backend     # <-- run Maven where pom.xml lives
        run: mvn -B -DskipTests clean package

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: backend/target/*.jar   # <-- upload the built JAR

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24573FE71F274CC585220D817E98090E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6F5C5C84F9714A19A33C629D0BDE038E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_43939A8B5F834E0891C383F9113FF169 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: gamerhub-api-fuhjf2dxdeaqdtgm   # <-- must match your App Service name
          slot-name: Production
          package: "*.jar"                          # JAR downloaded in current folder
